/*****************************************************************************************
    Name        : staticRecursiveHandler
    Desc        :Used to handel recursive trigger. Setting a static boolean to true.
---------------------------------------------------------------------------
 Developer              Date            Description
---------------------------------------------------------------------------
Jitendra Behera       25/04/2015          Created
******************************************************************************************/
public class staticRecursiveHandler {
public static boolean runOnetime = true;
}