/*
*****************************************************************************************
    Name        : trimblecorpComTnvcussfdcoutbound_v5Test 
                            
---------------------------------------------------------------------------
 Developer              Date            Description
---------------------------------------------------------------------------
 P M Mamata           19/07/2015          Created
*****************************************************************************************
*/

@isTest(seeAllData=true)
private class trimblecorpComTnvcussfdcoutbound_v5Test{
    static testmethod void testtrimble(){
        trimblecorpComTnvcussfdcoutbound_v5 tc = new trimblecorpComTnvcussfdcoutbound_v5();
        trimblecorpComTnvcussfdcoutbound_v5.tnvcusSFDCOutboundInput_element tn = new trimblecorpComTnvcussfdcoutbound_v5.tnvcusSFDCOutboundInput_element();
        trimblecorpComTnvcussfdcoutbound_v5.FlexAttributeType fl = new trimblecorpComTnvcussfdcoutbound_v5.FlexAttributeType();
        trimblecorpComTnvcussfdcoutbound_v5.DivisionType dv = new trimblecorpComTnvcussfdcoutbound_v5.DivisionType();
        trimblecorpComTnvcussfdcoutbound_v5.tnvcusSFDCOutboundOutput_element ts = new trimblecorpComTnvcussfdcoutbound_v5.tnvcusSFDCOutboundOutput_element();
        trimblecorpComTnvcussfdcoutbound_v5.RelationshipObjType rt = new trimblecorpComTnvcussfdcoutbound_v5.RelationshipObjType();  
        trimblecorpComTnvcussfdcoutbound_v5.FlexType ft = new trimblecorpComTnvcussfdcoutbound_v5.FlexType();
        trimblecorpComTnvcussfdcoutbound_v5.AddressType ad = new trimblecorpComTnvcussfdcoutbound_v5.AddressType();
        trimblecorpComTnvcussfdcoutbound_v5.ContactType ct = new trimblecorpComTnvcussfdcoutbound_v5.ContactType();
        trimblecorpComTnvcussfdcoutbound_v5.RelationshipAttributeType rat = new trimblecorpComTnvcussfdcoutbound_v5.RelationshipAttributeType();
        trimblecorpComTnvcussfdcoutbound_v5.AccountType at = new trimblecorpComTnvcussfdcoutbound_v5.AccountType();
        trimblecorpComTnvcussfdcoutbound_v5.HeaderType ht = new trimblecorpComTnvcussfdcoutbound_v5.HeaderType();
    }
    

}